replace default script version

diff --git a/create-factory-reset b/create-factory-reset
--- a/create-factory-reset
+++ b/create-factory-reset
@@ -1,43 +1,86 @@
 #!/bin/bash
 
 # fail on errors, undefined variables, and errors in pipes
-set -eu
-set -o pipefail
+set -eu -o pipefail
 
-
-# get current source dir, even if its hidden in links
-# needed for full paths relative to this script
-SOURCE="${BASH_SOURCE[0]}"
-while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
-  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
-  SOURCE="$(readlink "$SOURCE")"
-  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
-done
-DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
 
 source "$DIR/lib/display_funcs"
 source "$DIR/lib/usage.sh"
 source "$DIR/lib/setup.sh"
 source "$DIR/lib/utils.sh"
+source "$DIR/lib/stages.sh"
 
-echo "OPTION_BASE is ${OPTION_BASE}"
-echo "BASE is $BASE"
+show_setup_var_summary
 
+# this is to cleanup any previous runs that didn't run cleanup at the end
 if [ ! -z "${OPTION_CLEANUP_PRE}" ]; then
   cleanup
 fi
 
-check_prerequisites
-check_sources
-check_distribution
+if [ "$OPT_DO_CHECKS" ] ; then
+  check_prerequisites
+  check_sources
+fi
 
-echo "OPTION_DO_MAIN $OPTION_DO_MAIN"
+# extract the partition start/sizes for the source image
+[ "$OPT_GET_PART_FOR_ORIG" ] && get_partitions_for_original
 
-[ -z "${OPTION_DO_MAIN}" ] || main
+# extract start/sizes for lite image (if used)
+[ "$OPT_GET_PART_FOR_LITE" ] && get_partitions_for_lite
 
-if [ ! -z "${OPTION_CLEANUP_POST}" ]; then
+# to avoid conflicts, generate uuids for boot, recovery, root partions
+[ "$OPT_MAKE_UUIDS" ] && make_uuids
+
+# mount the boot and root partiions of source img to loopback devices
+[ "$OPT_MOUNT_ORIG" ] && make_loop_and_mount_original
+
+# make a writable copy of the source and mount it
+[ "$OPT_MOUNT_COPY" ] && make_loop_and_mount_copy
+
+# copy the partitions from the source into the writable copy
+[ "$OPT_COPY_TO_COPY" ] && copy_original_to_copy
+
+# # insert the correct UUID into the rootfs fstab from those generated earlier
+[ "$OPT_FIX_ROOTFS_FSTAB" ] && fix_copy_rootfs_fstab
+
+# # the resize script fails if the root partiion is not in position 2
+# so this needs to be copied into the copy image
+[ "$OPT_FIX_RESIZE_SCRIPT" ] && fix_resize_script
+
+# zip the copy of the rootfs for use in restoring
+[ "$OPT_MAKE_RECOVERY_ZIP" ] && output_zipped_copy_rootfs
+
+# going to use the lite image for the recovery partition
+[ "$OPT_MOUNT_LITE" ] && make_loop_and_mount_lite
+
+# calcule the required bytes and sectors for the restore p2 partition
+# from the recovery.zip plus the used space on the lite p2 partition
+[ "$OPT_GET_RECOVERY_SIZES" ] && get_recovery_root_part_size
+
+# use the values to create a restore img file and mount it
+[ "$OPT_MOUNT_RESTORE" ] && make_loop_and_mount_restore
+
+# copy the various source partiions into the restore image
+# mount the partitions for further editing
+[ "$OPT_COPY_TO_RESTORE" ] && copy_to_restore
+
+# edit the cmdline.txt file for correct partition
+[ "$OPT_FIX_CMDLINE_TXT" ] && overwrite_cmdline_for_boot
+
+# restore triggers the recovery from the running rpi
+[ "$OPT_MAKE_RESTORE_SCRIPT" ] && make_restore_script
+
+# recovery is triggered after reboot to restore partition
+[ "$OPT_MAKE_RECOVERY_SCRIPT" ] && make_recovery_script
+
+get_postbuild_summary
+
+# enable_rpi_serial_console
+
+if [ "${OPTION_CLEANUP_POST}" ]; then
   cleanup
 fi
 
 pr_header "finished"
-echo "BASE is $BASE.restore.img"
+pr_info "RESTORE image is $BASE.restore.img"
