adding dynamic loopback device names

diff --git a/files/create-factory-reset b/files/create-factory-reset
--- a/files/create-factory-reset
+++ b/files/create-factory-reset
@@ -1,98 +1,83 @@
 #!/bin/bash
 
-# fail on errors
-set -e
+# fail on errors, undefined variables, and errors in pipes
+set -eu
+set -o pipefail
 
 # BASE=2018-03-13-raspbian-stretch-lite
 # BASE=2018-06-27-raspbian-stretch-lite
 BASE=2018-10-09-raspbian-stretch-lite
 
-raspian_lite_06_27_sha256=3271b244734286d99aeba8fa043b6634cad488d211583814a2018fc14fdca313
-
-init_resize_script=~/ansible/roles/limepepper.raspberrypi/files/init_resize2.sh
+MOTD_SHOW_LIVE=""
+SET_PI_PASSWORD=""
 
 function main()
 {
 
-# base image file
+  pr_header "entering main function"
+
+# paths for base, intermediate and restore images
 IMG_ORIG=${BASE}.img
+[ -f ${IMG_ORIG} ] || { echo "Not found source image '${IMG_ORIG}'" && exit;  }
 
-# img to create (this is the file that should be flashed out)
 IMG_RESTORE=${BASE}.restore.img
-
-# img for use as the source of the rootfs, used as intermediate image
 IMG_LIVE=${BASE}.live.img
 
-# path to file that is used...???
-RECOVERY_SCRIPT=/usr/lib/raspi-config/init_resize2.sh
+# paths to src/dest file that is used for resetting in live image
+RECOVERY_SCRIPT_SOURCE="${DIR}/init_resize2.sh"
+[ -f ${RECOVERY_SCRIPT_SOURCE} ] || { echo "Not found ${RECOVERY_SCRIPT_SOURCE}" && exit;  }
+RECOVERY_SCRIPT_TARGET=/usr/lib/raspi-config/init_resize2.sh
 
-# because cloning, need to generate new UUIDs, partuuid get reset
-# UUID_BOOT=$(tr -dc 'a-f0-9' < /dev/urandom 2>/dev/null  | \
-#         dd bs=1 count=8 2>/dev/null)
+# because of cloning the images, need to generate new UUIDs
 UUID_RESTORE=$(uuidgen)
 UUID_ROOTFS=$(uuidgen)
 
+# @TODO using the existing UUID_BOOT because it stays the same
+# UUID_BOOT=$(tr -dc 'a-f0-9' < /dev/urandom 2>/dev/null  | \
+#         dd bs=1 count=8 2>/dev/null)
+
 # partuuid seems to get reset by resize.sh, however UUID doesn't seem to work
+set +o pipefail
 PARTUUID=$(tr -dc 'a-f0-9' < /dev/urandom 2>/dev/null | head -c8)
-pr_header "PARTUUID generated is ${PARTUUID}"
+set -o pipefail
+[ ! -z ${PARTUUID} ] || { echo "PARTUUID is empty '${PARTUUID}'" && exit;  }
 
-# also should inspect first...
-pr_header "1.1 detach any existing loop devices, mounts"
-
-sudo losetup --detach-all
-
-sudo umount -f -d mnt/restore_boot || true
-sudo umount -f mnt/restore_boot || true
-
-sudo umount -f -d mnt/restore_rootfs || true
-sudo umount -f mnt/restore_rootfs || true
-
-sudo umount -f -d mnt/restore_recovery || true
-sudo umount -f mnt/restore_recovery || true
+pr_ok "PARTUUID generated is ${PARTUUID}"
 
 pr_header "2.2 make a copy of the pristine image for use as the live rootfs"
 
 [[ -f "${IMG_LIVE}" ]] && \
 {
-  pr_warn "live file ${IMG_LIVE} already, exists"
+  pr_warn "live file ${IMG_LIVE} already, exists - overwriting"
+  cp -f ${IMG_ORIG} ${IMG_LIVE}
+  pr_ok "${IMG_LIVE} created"
 } || \
 {
   cp -f ${IMG_ORIG} ${IMG_LIVE}
   pr_ok "${IMG_LIVE} created"
 }
 
-pr_header "2.3 create an img file for boot, recovery, rootfs filesystems"
+pr_header "2.3 create an img file for boot, recovery, and rootfs filesystems"
 
-# this would need to be much bigger for the desktop/full fat img
-[[ -f "${IMG_RESTORE}" ]] && \
-{
-  pr_warn "restore file ${IMG_RESTORE} already, exists"
-} || \
-{
-  dd if=/dev/zero bs=4M count=1000 > ${IMG_RESTORE}
-  # touch ${IMG_RESTORE}
-}
+PT_ORIG="$(sfdisk -d ${IMG_ORIG})"
 
-pr_header "2.4 Verify that the img file was created"
-fdisk -lu ${IMG_RESTORE}
-
-pr_header "2.5 create the filesystem on the img file"
-
-# PTABLE_ID=$(echo $PTABLE | jq '.partitiontable.id')
-
-PTABLE="$(sfdisk -d ${IMG_ORIG})"
 #get the device name for use in the greps
-PTABLE_DEVICE=$(echo "${PTABLE}" | egrep '^device: ' | cut -d' ' -f2)
+PTABLE_DEVICE=$(echo "${PT_ORIG}" | egrep '^device: ' | cut -d' ' -f2)
+
 #get the existing sector start/sizes
-PTABLE_P1_START=$(echo "${PTABLE}" | egrep "^${PTABLE_DEVICE}1" | tr -s ' '| cut -d' ' -f4 | tr -d ',')
-PTABLE_P1_SIZE=$(echo "${PTABLE}" | egrep "^${PTABLE_DEVICE}1" | tr -s ' '| cut -d' ' -f6 | tr -d ',')
-PTABLE_P2_START=$(echo "${PTABLE}" | egrep "^${PTABLE_DEVICE}2" | tr -s ' '| cut -d' ' -f4 | tr -d ',')
-PTABLE_P2_SIZE=$(echo "${PTABLE}" | egrep "^${PTABLE_DEVICE}2" | tr -s ' '| cut -d' ' -f6 | tr -d ',')
+PTABLE_P1_START=$(echo "${PT_ORIG}" | egrep "^${PTABLE_DEVICE}1" | tr -s ' '| cut -d' ' -f4 | tr -d ',')
+PTABLE_P1_SIZE=$(echo "${PT_ORIG}" | egrep "^${PTABLE_DEVICE}1" | tr -s ' '| cut -d' ' -f6 | tr -d ',')
+
+PTABLE_P2_START=$(echo "${PT_ORIG}" | egrep "^${PTABLE_DEVICE}2" | tr -s ' '| cut -d' ' -f4 | tr -d ',')
+PTABLE_P2_SIZE=$(echo "${PT_ORIG}" | egrep "^${PTABLE_DEVICE}2" | tr -s ' '| cut -d' ' -f6 | tr -d ',')
+
+# PT_ORIG_P3_START=$(echo "${PT_ORIG}" | egrep "^${PTABLE_DEVICE}2" | tr -s ' '| cut -d' ' -f4 | tr -d ',')
+# PTABLE_P3_SIZE=$(echo "${}" | egrep "^${PTABLE_DEVICE}2" | tr -s ' '| cut -d' ' -f6 | tr -d ',')
 
 echo "found boot partition at ${PTABLE_P1_START} with size ${PTABLE_P1_SIZE}"
 echo "found root partition at ${PTABLE_P2_START} with size ${PTABLE_P2_SIZE}"
 
-sudo fdisk -l 2018-06-27-raspbian-stretch-lite.img | grep 'Sector size'
+sudo fdisk -l ${IMG_ORIG} | grep 'Sector size'
 
 # set the size of the new recovery partition in bytes
 ## $(( 2 * 1024**3 )) e.g. 2GiB
@@ -100,7 +85,8 @@ sudo fdisk -l 2018-06-27-raspbian-stretch-lite.img | grep 'Sector size'
 P2_NEWSIZE_BYTES=2147483648
 
 # how many sectors is that?
-P2_SECTORS=$(( ${P2_NEWSIZE_BYTES} / 512 ))
+# P2_SECTORS=$(( ${P2_NEWSIZE_BYTES} / 512 ))
+P2_SECTORS=${PTABLE_P2_SIZE}
 echo "P2 sectors is ${P2_SECTORS}"
 
 P2_END=$(( PTABLE_P2_START + ${P2_SECTORS} ))
@@ -110,17 +96,24 @@ echo "P2_END is ${P2_END}"
 # start P3 at the next 8192 boundary after that
 PTABLE_P3_START=$(( ((((( P2_END * 512 ) / 8192) + 1) * 8192)/512) ))
 
+# this would need to be much bigger for the desktop/full fat img
+[[ -f "${IMG_RESTORE}" ]] && \
+{
+  pr_warn "restore file ${IMG_RESTORE} already, exists - overwriting"
+  dd if=/dev/zero bs=4M count=2000 > ${IMG_RESTORE}
+} || \
+{
+  dd if=/dev/zero bs=4M count=2000 > ${IMG_RESTORE}
+  # touch ${IMG_RESTORE}
+}
+
+pr_header "2.4 Verify that the img file was created"
+fdisk -lu ${IMG_RESTORE}
+
+pr_header "2.5 create the filesystem on the img file"
 pr_warn "making partition table..."
-cat <<EOL
-label: dos
-label-id: 0x${PARTUUID}
-unit: sectors
 
-${IMG_RESTORE}1 : start=${PTABLE_P1_START}, size=${PTABLE_P1_SIZE}, type=c
-${IMG_RESTORE}2 : start=${PTABLE_P2_START}, size=${P2_SECTORS}, type=83
-${IMG_RESTORE}3 : start=${PTABLE_P3_START}, size=${PTABLE_P2_SIZE}, type=83
-
-EOL
+#${IMG_RESTORE}2 : start=${PTABLE_P2_START}, size=${P2_SECTORS}, type=83
 
 sfdisk ${IMG_RESTORE} <<EOL
 label: dos
@@ -137,11 +130,10 @@ pr_header "2.6 Verify that the new filesystem structure"
 fdisk -lu ${IMG_RESTORE}
 
 pr_header "2.7 map the img file to loopback device"
-sudo losetup -v  --show -f -P ${IMG_RESTORE}
-#sudo losetup --show -f -P ${IMG_LIVE}
+LOOP_RESTORE=$(sudo losetup -v  --show -f -P ${IMG_RESTORE})
 
-pr_header "partprobe the device???"
-partprobe ${IMG_RESTORE}
+pr_header "partprobe the new loopback device - ${LOOP_RESTORE}"
+sudo partprobe ${LOOP_RESTORE}
 
 pr_header "show the partitions"
 losetup -a
@@ -149,31 +141,38 @@ losetup -a
 ##losetup --show -f -P /root/2018-03-13-raspbian-stretch-lite.restore.img
 
 pr_header "3.1 mount the partitions"
-#sudo partx --show /dev/loop0
+#sudo partx --show ${LOOP_RESTORE}
 
 pr_header "find the partitions and add them to loopXpX devices"
-#sudo partx -v --add /dev/loop0
+#sudo partx -v --add ${LOOP_RESTORE}
 
 pr_header "3.3 map the live img to loopback device"
 # losetup -v -f ${IMG_LIVE}
-# partx -v --add /dev/loop0
-sudo losetup --show -f -P ${IMG_LIVE}
+# partx -v --add ${LOOP_RESTORE}
+LOOP_LIVE=$(sudo losetup --show -f -P ${IMG_LIVE})
+echo "LOOP LIVE is ${LOOP_LIVE}"
+sudo partprobe ${LOOP_LIVE}
 
 cat /proc/partitions
 sudo losetup -a
+sudo blkid
 
 pr_header "3.4 copy the filesystem partitions to the restore img"
-sudo dd if=/dev/loop1p1 of=/dev/loop0p1 bs=4M
-sudo dd if=/dev/loop1p2 of=/dev/loop0p2 bs=4M
-sudo dd if=/dev/loop1p2 of=/dev/loop0p3 bs=4M
+sudo dd if=${LOOP_LIVE}p1 of=${LOOP_RESTORE}p1 bs=4M
+sudo dd if=${LOOP_LIVE}p2 of=${LOOP_RESTORE}p2 bs=4M
+sudo dd if=${LOOP_LIVE}p2 of=${LOOP_RESTORE}p3 bs=4M
 
-pr_header "3.5 set the UUID_BOOT from the loop0p1"
-#mkdosfs -i ${UUID_BOOT} /dev/loop0p1
-UUID_BOOT=$(blkid -o export /dev/loop0p1 | egrep '^UUID=' | cut -d'=' -f2)
+# make sure the partitions on the loop device are available
+sudo partprobe ${LOOP_RESTORE}
 
-pr_warn "blkid -o export /dev/loop0p1  is $(blkid -o export /dev/loop0p1 )"
+pr_header "3.5 set the UUID_BOOT from the LOOP_LIVE"
+#mkdosfs -i ${UUID_BOOT} ${LOOP_RESTORE}p1
+UUID_BOOT=$(blkid -o export ${LOOP_LIVE}p1 | egrep '^UUID=' | cut -d'=' -f2)
+
+pr_warn "blkid -o export ${LOOP_RESTORE}p1  is $(blkid -o export ${LOOP_RESTORE}p1 )"
 pr_warn "UUID_BOOT is ${UUID_BOOT}"
 
+# fail if we didn't get the boot UUID
 [  -z "$UUID_BOOT" ] && \
 {
   echo "Empty: Yes"
@@ -181,31 +180,31 @@ pr_warn "UUID_BOOT is ${UUID_BOOT}"
 } || \
 {
   echo "Empty: No"
-  pr_warn "blkid -o export /dev/loop0p1  is $(blkid -o export /dev/loop0p1 )"
+  pr_warn "blkid -o export ${LOOP_RESTORE}p1 is $(blkid -o export ${LOOP_RESTORE}p1 )"
   pr_warn "UUID_BOOT is ${UUID_BOOT}"
 }
 
-pr_header "3.6 call tunefs"
-sudo tune2fs /dev/loop0p2 -U ${UUID_RESTORE}
-sudo e2label /dev/loop0p2 recoveryfs
-sudo tune2fs /dev/loop0p3 -U ${UUID_ROOTFS}
+pr_header "3.6 call tunefs to set label and UUID"
+sudo tune2fs ${LOOP_RESTORE}p2 -U ${UUID_RESTORE}
+sudo e2label ${LOOP_RESTORE}p2 recoveryfs
+sudo tune2fs ${LOOP_RESTORE}p3 -U ${UUID_ROOTFS}
 
 pr_header "3.7 call partprobe"
-sudo partprobe /dev/loop0
+sudo partprobe ${LOOP_RESTORE}
 
 pr_header "3.8 resize the fs on the recovery partition to fit the restore img"
-sudo e2fsck -f /dev/loop0p2
-sudo resize2fs /dev/loop0p2
+sudo e2fsck -f ${LOOP_RESTORE}p2
+sudo resize2fs ${LOOP_RESTORE}p2
 
-sudo fdisk -lu /dev/loop0
+sudo fdisk -lu ${LOOP_RESTORE}
 
 mkdir -p mnt/restore_boot
 mkdir -p mnt/restore_recovery
 mkdir -p mnt/restore_rootfs
 
-sudo mount /dev/loop0p1 mnt/restore_boot
-sudo mount /dev/loop0p2 mnt/restore_recovery
-sudo mount /dev/loop0p3 mnt/restore_rootfs
+sudo mount ${LOOP_RESTORE}p1 mnt/restore_boot
+sudo mount ${LOOP_RESTORE}p2 mnt/restore_recovery
+sudo mount ${LOOP_RESTORE}p3 mnt/restore_rootfs
 
 pr_header "4.0 current boot cmdline.txt"
 cat mnt/restore_boot/cmdline.txt
@@ -232,7 +231,7 @@ pr_header "4.2 backup original cmdline.txt"
 
 pr_header "4.3 create alt cmd file for recovery boot"
 sudo tee mnt/restore_boot/cmdline.txt_recovery << EOF
-dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=PARTUUID=XXXYYYXXX rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait init=${RECOVERY_SCRIPT}
+dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=PARTUUID=XXXYYYXXX rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait init=${RECOVERY_SCRIPT_TARGET}
 EOF
 ## not working;
 # init=/boot/factory_reset_restore
@@ -264,33 +263,11 @@ echo "factory restore script"
 
 EOF
 
-pr_header "4.6 create factory reset script - run this from live"
-sudo tee mnt/restore_boot/factory_reset_restore << 'EOF'
-#!/bin/sh
-
-echo "factory restore script"
-
-# dd bs=4M if=/opt/recovery.img of=/dev/mmcblk0p3 conv=fsync status=progress
-unzip -p /opt/recovery.img.zip \
-      | dd bs=4M \
-        of=/dev/mmcblk0p3 \
-        conv=fsync \
-        status=progress
-
-cp -f /boot/cmdline.txt_original /boot/cmdline.txt
-touch /boot/ssh
-
-reboot
-
-EOF
+sudo chmod +x mnt/restore_boot/factory_reset
 
 pr_header "4.7 copy init_resize2.sh to recovery"
-sudo cp ${init_resize_script} mnt/restore_recovery${RECOVERY_SCRIPT}
-sudo chmod +x mnt/restore_recovery${RECOVERY_SCRIPT}
-
-
-sudo chmod +x mnt/restore_boot/factory_reset
-sudo chmod +x mnt/restore_boot/factory_reset_restore
+sudo cp "${RECOVERY_SCRIPT_SOURCE}" "mnt/restore_recovery${RECOVERY_SCRIPT_TARGET}"
+sudo chmod +x "mnt/restore_recovery${RECOVERY_SCRIPT_TARGET}"
 
 pr_header "4.8 current boot cmdline.txt"
 cat mnt/restore_boot/cmdline.txt
@@ -322,6 +299,13 @@ UUID=${UUID_RESTORE}    /      ext4    defaults,noatime  0       1
 EOF
 
 pr_header "indicate this it is the live shell"
+[  -z "$MOTD_SHOW_LIVE" ] && \
+{
+  echo "not editing live message"
+
+} || \
+{
+
 sudo tee mnt/restore_rootfs/etc/motd << EOF
 ##    _     _____     _______
 ##   | |   |_ _\ \   / / ____|
@@ -330,6 +314,9 @@ sudo tee mnt/restore_rootfs/etc/motd << EOF
 ##   |_____|___|  \_/  |_____|
 ##
 EOF
+
+}
+
 
   pr_header "current live fstab"
   cat mnt/restore_rootfs/etc/fstab
@@ -391,25 +378,8 @@ pr_header "change the pi user password"
 
   pr_header "copy the recovery image to the recovery /opt dir for restoring"
 
-  # dd if=/dev/loop0p3 of=mnt/restore_recovery/opt/recovery.img bs=4M
-  sudo dd bs=4M if=/dev/loop0p3 | sudo zip mnt/restore_recovery/opt/recovery.img.zip -
-
-  # time dd bs=4M if=/dev/loop0p3 of=~/Downloads/recovery.img
-  # stat ~/Downloads/recovery.img
-  # time dd bs=4M if=/dev/loop0p3 | gzip > ~/Downloads/recovery.img.gz
-  # stat ~/Downloads/recovery.img.gz
-  # it seems like you can get a bit smaller with bzip, but its much slower
-  # time dd bs=4M if=/dev/loop0p3 | bzip2 --best > ~/Downloads/recovery.img.best.bz2
-  # stat ~/Downloads/recovery.img.best.bz2
-  # time dd bs=4M if=/dev/loop0p3 | bzip2 --fast > ~/Downloads/recovery.img.fast.bz2
-  # stat ~/Downloads/recovery.img.fast.bz2
-  # time dd bs=4M if=/dev/loop0p3 | bzip2 --small > ~/Downloads/recovery.img.small.bz2
-  # stat ~/Downloads/recovery.img.small.bz2
-  # time dd bs=4M if=/dev/loop0p3 | zip ~/Downloads/recovery.img.zip -
-  # stat ~/Downloads/recovery.img.zip
-
-  # | gzip > /media/disk/sda2-backup-10august09.gz
-  #  | bzip2 --best > /media/disk/$(date +%Y%m%d_%H%M%S)_sda2-backup.bz2
+  # dd if=${LOOP_RESTORE}p3 of=mnt/restore_recovery/opt/recovery.img bs=4M
+  sudo dd bs=4M if=${LOOP_RESTORE}p3 | sudo zip mnt/restore_recovery/opt/recovery.img.zip -
 
 
 
@@ -421,13 +391,15 @@ pr_header "change the pi user password"
 
 function cleanup()
 {
+
   pr_header "don't need partitions anymore unmount"
-  sudo umount -f -d mnt/restore_boot
-  sudo umount -f -d mnt/restore_rootfs
-  sudo umount -f -d mnt/restore_recovery
+  sudo umount -f -d mnt/restore_boot || true
+  sudo umount -f -d mnt/restore_rootfs || true
+  sudo umount -f -d mnt/restore_recovery || true
 
   pr_header "detach loop devices"
   sudo losetup --detach-all
+
 }
 
 # get current source dir, even if its hidden in links
@@ -439,7 +411,10 @@ while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symli
 done
 DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
 
-source ${DIR}/display_funcs
+source "${DIR}/display_funcs"
+
+# if the script failed, cleanup previous run.
+# cleanup
 
 main
 
